name: ci

on:
  push:
    branches:
      - 'main'
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm ci
      - run: npx semantic-release
